### ISSUE TITLE
Support credentials without id

### ISSUE THREAD

**Issue by clehner** [spruceid/credible#31]
A Verifiable Credential without an [`id`](https://w3c.github.io/vc-data-model/#identifiers) property is allowed in the [VC Data Model](https://github.com/w3c/vc-data-model). Currently Credible relies on the `id` property to identify credentials internally.

**Comment by bumblefudge** [comment]
Would it make sense to failover to a hash of the payload, or the proof, or some other pseudorandom string?

I would also like to upvote arbitrary "aliasing" or "petnaming" of credentials by users.  Given that the various use-cases we're working on all listed offered credentials by title and/or by a "purpose" string, I would think the title or purpose string should be the default alias, and an intuitive option should be available for replacing this with an arbitrary string.  I'm currently working on a mockup that would make clear the self-organizing UX assumptions I'm describing here.

**Comment by bumblefudge** [comment]
i also saw a thread on DIF Slack last week where someone recommended using hash of current block of <chose your favorite public blockchain>, since it's a pseudorandom that doubles as a redundant timestamp :D
