### ISSUE TITLE
Error: Expected a value of type 'FutureOr<JSObject<CryptoKey>>?', but got one of type 'CryptoKey'

### ISSUE THREAD

**Issue by neilb14** [spruceid/credible#47]
I'm getting the following exception on the Private Key Generation screen while running in Chrome:

```
Uncaught (in promise) Error: Expected a value of type 'FutureOr<JSObject<CryptoKey>>?', but got one of type 'CryptoKey'
    at Object.throw_ [as throw] (errors.dart:251)
    at Object.castError (errors.dart:84)
    at Object.cast [as as] (operations.dart:442)
    at dart.NullableType.new.as (types.dart:417)
    at js_util.dart:183
```

Output of flutter doctor:
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.3 20E232 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)

I'm pretty sure this is a duplicate of https://github.com/dart-lang/sdk/issues/44499 but wondering if you have a workaround.

**Comment by sbihel** [comment]
Hiya, what command did you run? Have you enabled the `--no-sound-null-safety` option?

**Comment by w4ll3** [comment]
Interesting, I thought that this was already resolved, are you at the latest main? It seems to have a workaround [here](https://github.com/dart-lang/sdk/issues/45745).

**Comment by neilb14** [comment]
Thanks for your quick responses @sbihel and @w4ll3!! 

I am running `flutter run --no-sound-null-safety` and indeed on the latest commit of main.

Also, looks like I'm on Dart SDK 2.14.0:
```
10:04:47 ~/l/s/credible> flutter --version
Flutter 2.3.0-0.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision d72bfb8d07 (8 days ago) • 2021-04-26 06:05:55 -0700
Engine • revision de6e1adf97
Tools • Dart 2.14.0 (build 2.14.0-18.0.dev)
```

**Comment by grsouza** [comment]
I've tested with the latest main and it seems to be working, can you try that again @neilb14?

Have you successfully built didkit for wasm?

Try running `flutter run -d chrome` without the `--no-sound-null-safety` flag, as it isn't needed anymore.

Here is my `flutter --version` output for comparison.

```sh
$ flutter --version
Flutter 2.5.0-5.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0f465e5b2a (13 days ago) • 2021-08-04 18:59:50 -0400
Engine • revision a0d89b1a54
Tools • Dart 2.14.0 (build 2.14.0-377.0.dev)
```

**Comment by neilb14** [comment]
Yes, I've confirmed that it's working now, thanks.
