### ISSUE TITLE
Credentials list is not being reloaded after a credential being removed

### ISSUE THREAD

**Issue by grsouza** [spruceid/credible#73]
If the user removes a credential, once he goes back to the list, the list doesn't get reloaded automatically.

**Comment by theosirian** [comment]
From what I could test, it doesn't always happen. There is code to reload the list after deletion and the page should reflect the list changes even after closing the details page, but it seems the list is reloaded before the changes are reflected to the database sometimes. Maybe we can add a hardcoded delay after deletion and hope the updated list is loaded after this set amount of time.

**Comment by hawkbee1** [comment]
The list is build once in a stateless Widget when your open app or use the menu. When you delete item you just do a pop.
If you build the list directly with data from the store you would have:
- automatic update of the list,
- Opportunity to display something specific when list is empty
