### ISSUE TITLE
can't find libdidkit.so on fresh android install

### ISSUE THREAD

**Issue by hawkbee1** [spruceid/credible#89]
Fresh install for ios is working fine.

When building for android, I don't have any error message.
The credible app is launching but when DynamicLibrary.open('libdidkit.so') occurs I have an error message : libdidkit.so.
here's the list of libdidkit.so files I have in my spruceid folder : 
./didkit/target/debug/libdidkit.so
./didkit/target/debug/deps/libdidkit.so
./didkit/target/release/libdidkit.so
./didkit/target/release/deps/libdidkit.so
./didkit/target/armv7-linux-androideabi/release/libdidkit.so
./didkit/target/armv7-linux-androideabi/release/deps/libdidkit.so
./didkit/target/aarch64-linux-android/release/libdidkit.so
./didkit/target/aarch64-linux-android/release/deps/libdidkit.so
./didkit/target/x86_64-linux-android/release/libdidkit.so
./didkit/target/x86_64-linux-android/release/deps/libdidkit.so
./didkit/target/i686-linux-android/release/libdidkit.so
./didkit/target/i686-linux-android/release/deps/libdidkit.so
./didkit/lib/android/didkit/src/main/jniLibs/x86/libdidkit.so
./didkit/lib/android/didkit/src/main/jniLibs/arm64-v8a/libdidkit.so
./didkit/lib/android/didkit/src/main/jniLibs/x86_64/libdidkit.so
./didkit/lib/android/didkit/src/main/jniLibs/armeabi-v7a/libdidkit.so
./didkit/lib/flutter/android/src/main/jniLibs/arm64-v8a/libdidkit.so
./didkit/lib/flutter/android/src/main/jniLibs/x86_64/libdidkit.so
./didkit/lib/flutter/android/src/main/jniLibs/armeabi-v7a/libdidkit.so
./didkit/lib/flutter/libdidkit.so
./didkit/lib/python/didkit/libdidkit.so

So I don't have any libdidkit.so files in credible/build/ folders

**Comment by grsouza** [comment]
Hey @hawkbee1 indeed we have an issue on `didkit`, can you checkouts didkit's `fix/flutter-symlink` branch and try again.
I've tested with the fix on this branch and now it's seems to be working.

I'll be opening a PR and linking this issue.

**Comment by shabaadh** [comment]
> Fresh install for ios is working fine.
> 
> When building for android, I don't have any error message. The credible app is launching but when DynamicLibrary.open('libdidkit.so') occurs I have an error message : libdidkit.so. here's the list of libdidkit.so files I have in my spruceid folder : ./didkit/target/debug/libdidkit.so ./didkit/target/debug/deps/libdidkit.so ./didkit/target/release/libdidkit.so ./didkit/target/release/deps/libdidkit.so ./didkit/target/armv7-linux-androideabi/release/libdidkit.so ./didkit/target/armv7-linux-androideabi/release/deps/libdidkit.so ./didkit/target/aarch64-linux-android/release/libdidkit.so ./didkit/target/aarch64-linux-android/release/deps/libdidkit.so ./didkit/target/x86_64-linux-android/release/libdidkit.so ./didkit/target/x86_64-linux-android/release/deps/libdidkit.so ./didkit/target/i686-linux-android/release/libdidkit.so ./didkit/target/i686-linux-android/release/deps/libdidkit.so ./didkit/lib/android/didkit/src/main/jniLibs/x86/libdidkit.so ./didkit/lib/android/didkit/src/main/jniLibs/arm64-v8a/libdidkit.so ./didkit/lib/android/didkit/src/main/jniLibs/x86_64/libdidkit.so ./didkit/lib/android/didkit/src/main/jniLibs/armeabi-v7a/libdidkit.so ./didkit/lib/flutter/android/src/main/jniLibs/arm64-v8a/libdidkit.so ./didkit/lib/flutter/android/src/main/jniLibs/x86_64/libdidkit.so ./didkit/lib/flutter/android/src/main/jniLibs/armeabi-v7a/libdidkit.so ./didkit/lib/flutter/libdidkit.so ./didkit/lib/python/didkit/libdidkit.so
> 
> So I don't have any libdidkit.so files in credible/build/ folders

I have an issue when using the command make ../target/test/android.stamp  in lib folder of did kit: 

Compiling didkit v0.6.0 (/Users/admin/Documents/flutter projects/didkit_demo/deps/didkit/lib)
error: linking with i686-linux-android19-clang failed: exit status: 1

@hawkbee1 @grdsdev May I know which Android idk version you guys are using ??
